export type MermaidTemplate = {
  id: string;
  name: string;
  family: "UML" | "General" | "Data" | "Planning";
  description: string;
  source: string;
  tips: string[];
  docsUrl: string;
};

export type MermaidSyntaxSection = {
  title: string;
  entries: Array<{ syntax: string; meaning: string }>;
};

export const MERMAID_SYNTAX_SECTIONS: MermaidSyntaxSection[] = [
  {
    title: "Threadwise easy syntax",
    entries: [
      { syntax: "uml class · uml sequence · uml state", meaning: "Start a UML diagram without remembering Mermaid's header names." },
      { syntax: "flow", meaning: "Start a vertical flowchart." },
      { syntax: "Child extends Parent", meaning: "Class inheritance." },
      { syntax: "Class implements Interface", meaning: "Interface implementation." },
      { syntax: "Whole contains Part · Whole has Part", meaning: "Composition or aggregation." },
      { syntax: "A uses B", meaning: "Class dependency." },
      { syntax: "public title: String", meaning: "Public class field; private, protected, and package also work." },
      { syntax: "public save()", meaning: "Public class method." },
      { syntax: "A sends B: message", meaning: "Sequence request." },
      { syntax: "B replies A: message", meaning: "Sequence response." },
      { syntax: "start -> Draft · Draft -> end", meaning: "Initial or final state transition." },
    ],
  },
  {
    title: "Every diagram",
    entries: [
      { syntax: "%% comment", meaning: "Add a comment on its own line." },
      { syntax: "Tab / Shift+Tab", meaning: "Indent or outdent selected diagram lines." },
      { syntax: '"Label with punctuation"', meaning: "Quote labels that contain punctuation or Unicode." },
      { syntax: "Layout menu", meaning: "Choose vertical or horizontal flowchart, class, and state layouts without editing syntax." },
    ],
  },
  {
    title: "Flowcharts",
    entries: [
      { syntax: "A[Rectangle]", meaning: "Process node." },
      { syntax: "B(Rounded)", meaning: "Rounded process node." },
      { syntax: "C{Decision}", meaning: "Decision node." },
      { syntax: "D((Circle))", meaning: "Circular node." },
      { syntax: "A --> B", meaning: "Solid arrow." },
      { syntax: "A -.-> B", meaning: "Dotted arrow." },
      { syntax: "A ==>|label| B", meaning: "Thick labelled arrow." },
      { syntax: "subgraph Name … end", meaning: "Group related nodes." },
    ],
  },
  {
    title: "Sequence UML",
    entries: [
      { syntax: "actor User", meaning: "Declare a person-shaped actor." },
      { syntax: "participant API", meaning: "Declare a participant and its order." },
      { syntax: "A->>B: Request", meaning: "Solid message." },
      { syntax: "B-->>A: Reply", meaning: "Dotted response." },
      { syntax: "activate B / deactivate B", meaning: "Show an activation bar." },
      { syntax: "Note over A,B: Text", meaning: "Place a note over participants." },
      { syntax: "loop · alt/else · opt · par/and", meaning: "Describe repeated or conditional interactions; close with end." },
    ],
  },
  {
    title: "Class UML",
    entries: [
      { syntax: "+ public · - private · # protected · ~ package", meaning: "Member visibility." },
      { syntax: "Parent <|-- Child", meaning: "Inheritance." },
      { syntax: "Whole *-- Part", meaning: "Composition." },
      { syntax: "Whole o-- Part", meaning: "Aggregation." },
      { syntax: "A --> B", meaning: "Association." },
      { syntax: "A ..> B", meaning: "Dependency." },
      { syntax: 'A "1" o-- "many" B', meaning: "Add multiplicity and a relationship." },
      { syntax: "<<interface>>", meaning: "Add a classifier annotation inside a class." },
    ],
  },
  {
    title: "State UML",
    entries: [
      { syntax: "[*] --> Draft", meaning: "Initial state." },
      { syntax: "Draft --> Saved : autosave", meaning: "Labelled transition." },
      { syntax: "Saved --> [*]", meaning: "Final state." },
      { syntax: 'state "Readable name" as shortName', meaning: "Alias a state." },
      { syntax: "state Parent { … }", meaning: "Create a composite state." },
      { syntax: "--", meaning: "Split a composite state into concurrent regions." },
    ],
  },
  {
    title: "Data and planning",
    entries: [
      { syntax: "A ||--o{ B : has", meaning: "ER: one A to zero-or-many B records." },
      { syntax: "section Name", meaning: "Group Gantt, journey, or timeline entries." },
      { syntax: "Task :id, 2026-09-01, 3d", meaning: "Gantt task with id, start date, and duration." },
      { syntax: "Task : 4 : Student, Tutor", meaning: "Journey task, score from 1–5, then actors." },
      { syntax: '"Slice" : 40', meaning: "Pie-chart label and numeric value." },
    ],
  },
];

export const MERMAID_TEMPLATES: MermaidTemplate[] = [
  {
    id: "flowchart",
    name: "Flowchart",
    family: "General",
    description: "Processes, choices, and connected ideas.",
    source: [
      "flowchart LR",
      '  Capture["Capture note"] --> Decide{Ready to file?}',
      '  Decide -->|Yes| File["Save to module"]',
      '  Decide -->|No| Draft["Keep autosaving"]',
      "  Draft --> Capture",
    ].join("\n"),
    tips: ["Use the diagram card's Layout menu for top-to-bottom or left-to-right.", "You can type `flow` as the first line.", "Quote labels with punctuation."],
    docsUrl: "https://mermaid.js.org/syntax/flowchart.html",
  },
  {
    id: "sequence-uml",
    name: "Sequence diagram",
    family: "UML",
    description: "Messages exchanged over time between people or systems.",
    source: [
      "sequenceDiagram",
      "  actor Student",
      "  participant Dashboard",
      "  participant API",
      "  Student->>Dashboard: Save note",
      "  Dashboard->>API: Encrypt and store draft",
      "  activate API",
      "  API-->>Dashboard: New revision",
      "  deactivate API",
      "  Dashboard-->>Student: Saved across devices",
    ].join("\n"),
    tips: ["Participants appear in declaration order.", "Easy syntax accepts `A sends B: message` and `B replies A: message`.", "Sequence diagrams keep participants across and time flowing downward."],
    docsUrl: "https://mermaid.js.org/syntax/sequenceDiagram.html",
  },
  {
    id: "class-uml",
    name: "Class diagram",
    family: "UML",
    description: "Classes, members, interfaces, and structural relationships.",
    source: [
      "classDiagram",
      "  class Note {",
      "    +String title",
      "    +String body",
      "    +save()",
      "  }",
      "  class Module {",
      "    +String code",
      "  }",
      '  Module "1" o-- "many" Note : contains',
    ].join("\n"),
    tips: ["Try `public title: String` or `public save()` inside a class.", "Try `Child extends Parent`, `Whole contains Part`, or `Whole has Part`.", "Use the card's Layout menu instead of typing a direction."],
    docsUrl: "https://mermaid.js.org/syntax/classDiagram.html",
  },
  {
    id: "state-uml",
    name: "State diagram",
    family: "UML",
    description: "Lifecycle states and the events that move between them.",
    source: [
      "stateDiagram-v2",
      "  [*] --> Draft",
      "  Draft --> Saved : autosave",
      "  Saved --> Draft : keep writing",
      "  Saved --> Filed : choose module",
      "  Filed --> [*]",
    ].join("\n"),
    tips: ["Easy syntax accepts `start -> Draft`, `Draft -> Saved: autosave`, and `Saved -> end`.", "Use the card's Layout menu instead of typing a direction.", "Use state Name { … } for nested states."],
    docsUrl: "https://mermaid.js.org/syntax/stateDiagram.html",
  },
  {
    id: "entity-relationship",
    name: "Entity relationship",
    family: "Data",
    description: "Data entities, fields, and cardinality.",
    source: [
      "erDiagram",
      "  USER ||--o{ NOTE : creates",
      "  MODULE ||--o{ NOTE : contains",
      "  NOTE {",
      "    string title",
      "    string body",
      "  }",
    ].join("\n"),
    tips: ["|| means exactly one; o{ means zero or many.", "Relationship labels follow a colon.", "Declare attributes inside braces."],
    docsUrl: "https://mermaid.js.org/syntax/entityRelationshipDiagram.html",
  },
  {
    id: "mindmap",
    name: "Mind map",
    family: "General",
    description: "A central topic with progressively indented branches.",
    source: [
      "mindmap",
      "  root((Exam plan))",
      "    Topics",
      "      Graphs",
      "      SQL",
      "    Practice",
      "      Tutorials",
      "      Past papers",
    ].join("\n"),
    tips: ["Indentation defines the hierarchy.", "Use ((text)) for a circular root.", "Tab and Shift+Tab adjust selected levels in Threadwise."],
    docsUrl: "https://mermaid.js.org/syntax/mindmap.html",
  },
  {
    id: "gantt",
    name: "Gantt chart",
    family: "Planning",
    description: "Tasks, dependencies, milestones, and dates.",
    source: [
      "gantt",
      "  title Project plan",
      "  dateFormat YYYY-MM-DD",
      "  section Research",
      "  Read sources :read, 2026-09-01, 3d",
      "  section Build",
      "  Draft solution :draft, after read, 4d",
      "  Submit :milestone, after draft, 0d",
    ].join("\n"),
    tips: ["Set dateFormat before dated tasks.", "Use after taskId for dependencies.", "Add milestone before a task id for a milestone."],
    docsUrl: "https://mermaid.js.org/syntax/gantt.html",
  },
  {
    id: "timeline",
    name: "Timeline",
    family: "Planning",
    description: "Events arranged in chronological order.",
    source: [
      "timeline",
      "  title Module milestones",
      "  Week 1 : Choose topic",
      "  Week 2 : Draft proposal : Get feedback",
      "  Week 3 : Submit",
    ].join("\n"),
    tips: ["Start each period at the same indentation.", "Add more events to one period with extra colons or lines.", "Periods can be words, dates, or numbers."],
    docsUrl: "https://mermaid.js.org/syntax/timeline.html",
  },
  {
    id: "journey",
    name: "User journey",
    family: "Planning",
    description: "Steps in an experience, scored by user sentiment.",
    source: [
      "journey",
      "  title Filing a study note",
      "  section Capture",
      "    Write freely: 5: Student",
      "    Check diagram: 4: Student",
      "  section File",
      "    Choose module: 4: Student",
      "    Find it later: 5: Student",
    ].join("\n"),
    tips: ["Scores run from 1 to 5.", "List actors after the score, separated by commas.", "Use sections to group stages."],
    docsUrl: "https://mermaid.js.org/syntax/userJourney.html",
  },
  {
    id: "pie",
    name: "Pie chart",
    family: "Data",
    description: "Simple proportions across named categories.",
    source: [
      "pie showData",
      "  title Study time",
      '  "Reading" : 35',
      '  "Practice" : 45',
      '  "Review" : 20',
    ].join("\n"),
    tips: ["Values must be positive numbers.", "showData displays the values.", "Quote every category label."],
    docsUrl: "https://mermaid.js.org/syntax/pie.html",
  },
  {
    id: "git-graph",
    name: "Git graph",
    family: "General",
    description: "Commits, branches, checkouts, and merges.",
    source: [
      "gitGraph",
      '  commit id: "Draft"',
      "  branch notes",
      "  checkout notes",
      '  commit id: "Add diagram"',
      "  checkout main",
      "  merge notes",
    ].join("\n"),
    tips: ["A main branch exists automatically.", "branch creates and checks out a branch.", "checkout and switch are interchangeable."],
    docsUrl: "https://mermaid.js.org/syntax/gitgraph.html",
  },
  {
    id: "quadrant",
    name: "Quadrant chart",
    family: "Planning",
    description: "Compare items along two named axes.",
    source: [
      "quadrantChart",
      "  title Task priority",
      "  x-axis Low effort --> High effort",
      "  y-axis Low impact --> High impact",
      "  quadrant-1 Plan carefully",
      "  quadrant-2 Do first",
      "  quadrant-3 Defer",
      "  quadrant-4 Quick wins",
      '  "Revise tutorial": [0.35, 0.75]',
      '  "Organise files": [0.20, 0.30]',
    ].join("\n"),
    tips: ["Coordinates run from 0 to 1.", "The first number is x; the second is y.", "Quote item labels."],
    docsUrl: "https://mermaid.js.org/syntax/quadrantChart.html",
  },
];
